steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/mlops-docker/train-gpu:latest',
    '-f',
    'dockerfiles/train_gpu.dockerfile'
  ]
  env:
    - 'DOCKER_BUILDKIT=1'
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/mlops-docker/train-gpu:latest',
  ]
options:
  logging: CLOUD_LOGGING_ONLY
