steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build container image'
  args: [
    'build',
    '.',
    '-t',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/mlops-docker/train-gpu:debug',
    '-f',
    'dockerfiles/train_gpu.dockerfile',
    '--build-arg',
    'CACHEBUST=$BUILD_ID',
    '--build-arg',
    'GIT_COMMIT_SHA=$COMMIT_SHA'
  ]
  env:
    - 'DOCKER_BUILDKIT=1'
- name: 'gcr.io/cloud-builders/docker'
  id: 'Push container image'
  args: [
    'push',
    'europe-west1-docker.pkg.dev/$PROJECT_ID/mlops-docker/train-gpu:debug'
  ]
options:
  logging: CLOUD_LOGGING_ONLY
